name: halloween
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/scary.mp3
    - assets/images/halloween.jpeg
    - assets/images/ghost.png
    - assets/images/zombie.png
    - assets/images/pumpkin.png
    - assets/images/trap.png



